In [1]:
import cv2

In [2]:
img = cv2.imread('/home/aman-py/Desktop/Face_recognition/galaxy.jpg',0)

In [3]:
print(type(img))

<class 'numpy.ndarray'>


In [4]:
img.shape

(1485, 990)

In [5]:
cv2.imshow('Galaxy',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
resize = cv2.resize(img,(300,300))
cv2.imwrite('New_Galaxy.jpg',resize)
cv2.imshow('Galaxy',resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
resize_img = cv2.resize(img,(img.shape[1],img.shape[0]))
cv2.imshow('Galaxy',resize_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
import cv2

In [20]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [21]:
img = cv2.imread('group.jpg')

In [25]:
gry_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gry_img,scaleFactor=1.5,minNeighbors=5)

In [26]:
for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),1)

In [ ]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
print(faces)

[[235  50  30  30]
 [270  51  28  28]
 [252 105  30  30]
 [318 125  30  30]
 [224 125  32  32]
 [148  81  31  31]
 [322  81  30  30]
 [225  83  32  32]
 [279  95  31  31]
 [243 247  35  35]
 [299 255  31  31]
 [447  77  39  39]
 [190  99  36  36]
 [ 99 144  36  36]
 [349 123  28  28]
 [ 76  64  50  50]
 [344 282  37  37]
 [142 137  39  39]
 [307 168  41  41]
 [161 261  43  43]
 [488  64  47  47]
 [396 238  44  44]
 [257 345  39  39]
 [421 299  52  52]
 [ 53  15 149 149]
 [139   6 193 193]]


In [ ]:
import cv2
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
img = cv2.imread('group.jpg')
gry_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gry_img,scaleFactor=1.05,minNeighbors=12)
for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),1)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2,time
video = cv2.VideoCapture(0)
first_frame = None
a =0
while True:
    check,frame = video.read()
    
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray,(21,21),0)
    
    if first_frame is None:
        first_frame = gray
        continue
    
    delta_frame = cv2.absdiff(first_frame,gray)
    threshold = cv2.threshold(delta_frame,50,255,cv2.THRESH_BINARY)[1]
    threshold = cv2.dilate(threshold,None,iterations=2)
    
    (_,cnts,_) = cv2.findContours(threshold.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)     #All Distinct Object Parameters in Threshold Frame
    
    for countour in cnts:
        
        if cv2.contourArea(countour) < 2500:
            continue
        (x,y,w,h) = cv2.boundingRect(countour)
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),3)

    cv2.imshow('Capturing...',gray)
    cv2.imshow('Delta Frame',delta_frame)
    cv2.imshow('Threshold Frame',threshold)
    cv2.imshow('Color Frame',frame)
    
    print(gray)
    print(delta_frame)
    
    key=cv2.waitKey(1)
    
    
    if key == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

[[144 144 144 ...  71  71  71]
 [144 144 144 ...  71  71  71]
 [144 144 144 ...  71  70  70]
 ...
 [ 92  91  91 ...  52  51  51]
 [ 91  91  91 ...  51  51  50]
 [ 91  91  91 ...  51  51  50]]
[[2 2 2 ... 3 3 3]
 [2 2 2 ... 3 3 3]
 [2 2 2 ... 3 3 3]
 ...
 [1 0 1 ... 2 2 2]
 [0 0 1 ... 1 2 1]
 [0 0 1 ... 1 2 1]]
[[141 141 142 ...  70  70  70]
 [141 141 142 ...  69  70  70]
 [141 141 141 ...  69  69  69]
 ...
 [ 90  89  89 ...  52  51  51]
 [ 90  89  89 ...  52  51  51]
 [ 89  89  89 ...  52  51  51]]
[[5 5 4 ... 4 4 4]
 [5 5 4 ... 5 4 4]
 [5 5 5 ... 5 4 4]
 ...
 [1 2 1 ... 2 2 2]
 [1 2 1 ... 2 2 2]
 [2 2 1 ... 2 2 2]]
[[142 142 142 ...  71  71  71]
 [142 142 142 ...  71  70  70]
 [142 142 142 ...  70  70  70]
 ...
 [ 86  86  85 ...  50  50  49]
 [ 86  86  85 ...  50  50  49]
 [ 86  86  85 ...  50  49  49]]
[[4 4 4 ... 3 3 3]
 [4 4 4 ... 3 4 4]
 [4 4 4 ... 4 3 3]
 ...
 [5 5 5 ... 0 1 0]
 [5 5 5 ... 0 1 0]
 [5 5 5 ... 0 0 0]]
[[140 140 140 ...  71  71  71]
 [140 140 140 ...  71  71  71]
 [

[[131 131 131 ...  65  65  65]
 [131 131 131 ...  65  65  65]
 [131 131 131 ...  65  65  65]
 ...
 [ 82  82  81 ...  58  58  58]
 [ 82  81  81 ...  58  58  57]
 [ 82  81  81 ...  58  57  57]]
[[15 15 15 ...  9  9  9]
 [15 15 15 ...  9  9  9]
 [15 15 15 ...  9  8  8]
 ...
 [ 9  9  9 ...  8  9  9]
 [ 9 10  9 ...  8  9  8]
 [ 9 10  9 ...  8  8  8]]
[[132 132 132 ...  63  63  63]
 [132 132 131 ...  63  63  63]
 [131 131 131 ...  63  63  63]
 ...
 [ 82  82  82 ...  56  56  56]
 [ 82  82  82 ...  56  55  55]
 [ 82  82  81 ...  56  55  55]]
[[14 14 14 ... 11 11 11]
 [14 14 15 ... 11 11 11]
 [15 15 15 ... 11 10 10]
 ...
 [ 9  9  8 ...  6  7  7]
 [ 9  9  8 ...  6  6  6]
 [ 9  9  9 ...  6  6  6]]
[[135 135 135 ...  63  64  64]
 [135 135 135 ...  63  63  64]
 [135 135 135 ...  63  63  63]
 ...
 [ 81  81  81 ...  59  59  59]
 [ 81  81  81 ...  59  59  59]
 [ 81  81  81 ...  59  59  59]]
[[11 11 11 ... 11 10 10]
 [11 11 11 ... 11 11 10]
 [11 11 11 ... 11 10 10]
 ...
 [10 10  9 ...  9 10 10]
 [10 10

[[132 132 133 ...  63  63  63]
 [132 132 132 ...  63  63  63]
 [132 132 132 ...  63  63  63]
 ...
 [ 77  77  78 ...  53  53  53]
 [ 77  77  78 ...  53  53  52]
 [ 77  77  78 ...  53  52  52]]
[[14 14 13 ... 11 11 11]
 [14 14 14 ... 11 11 11]
 [14 14 14 ... 11 10 10]
 ...
 [14 14 12 ...  3  4  4]
 [14 14 12 ...  3  4  3]
 [14 14 12 ...  3  3  3]]
[[133 133 133 ...  64  64  64]
 [133 133 133 ...  64  64  64]
 [133 133 133 ...  64  64  64]
 ...
 [ 78  78  78 ...  54  54  54]
 [ 78  78  78 ...  54  53  53]
 [ 78  78  78 ...  54  53  53]]
[[13 13 13 ... 10 10 10]
 [13 13 13 ... 10 10 10]
 [13 13 13 ... 10  9  9]
 ...
 [13 13 12 ...  4  5  5]
 [13 13 12 ...  4  4  4]
 [13 13 12 ...  4  4  4]]
[[131 131 131 ...  62  62  62]
 [131 131 131 ...  62  62  62]
 [131 131 131 ...  62  62  62]
 ...
 [ 79  80  80 ...  56  56  56]
 [ 79  79  80 ...  56  56  55]
 [ 79  79  80 ...  56  56  55]]
[[15 15 15 ... 12 12 12]
 [15 15 15 ... 12 12 12]
 [15 15 15 ... 12 11 11]
 ...
 [12 11 10 ...  6  7  7]
 [12 12

[[16 16 15 ... 10 10  9]
 [16 16 15 ... 10 10  9]
 [16 16 16 ... 10  9  8]
 ...
 [52 52 52 ...  0  1  1]
 [54 54 54 ...  0  1  1]
 [54 54 54 ...  0  1  1]]
[[131 131 131 ...  61  62  62]
 [131 131 131 ...  61  62  62]
 [131 131 131 ...  61  62  62]
 ...
 [ 36  36  35 ...  52  52  52]
 [ 35  34  34 ...  52  52  52]
 [ 34  34  33 ...  52  52  52]]
[[15 15 15 ... 13 12 12]
 [15 15 15 ... 13 12 12]
 [15 15 15 ... 13 11 11]
 ...
 [55 55 55 ...  2  3  3]
 [56 57 56 ...  2  3  3]
 [57 57 57 ...  2  3  3]]
[[131 131 131 ...  64  64  64]
 [131 131 131 ...  64  64  64]
 [131 131 131 ...  64  64  64]
 ...
 [ 35  34  34 ...  50  50  50]
 [ 33  33  32 ...  50  50  50]
 [ 33  33  32 ...  50  50  50]]
[[15 15 15 ... 10 10 10]
 [15 15 15 ... 10 10 10]
 [15 15 15 ... 10  9  9]
 ...
 [56 57 56 ...  0  1  1]
 [58 58 58 ...  0  1  1]
 [58 58 58 ...  0  1  1]]
[[129 129 129 ...  69  69  69]
 [129 129 129 ...  69  69  69]
 [129 129 129 ...  69  70  70]
 ...
 [ 31  31  31 ...  51  51  51]
 [ 30  30  30 ...  

[[131 131 132 ...  58  58  57]
 [131 131 132 ...  58  58  57]
 [131 131 131 ...  58  58  58]
 ...
 [ 60  59  57 ...  51  51  51]
 [ 61  60  58 ...  51  51  51]
 [ 62  61  58 ...  51  51  51]]
[[15 15 14 ... 16 16 17]
 [15 15 14 ... 16 16 17]
 [15 15 15 ... 16 15 15]
 ...
 [31 32 33 ...  1  2  2]
 [30 31 32 ...  1  2  2]
 [29 30 32 ...  1  2  2]]
[[129 129 129 ...  62  62  62]
 [129 129 129 ...  62  62  62]
 [129 129 129 ...  62  62  62]
 ...
 [ 23  23  23 ...  49  49  49]
 [ 23  23  23 ...  49  49  49]
 [ 23  23  23 ...  49  49  49]]
[[17 17 17 ... 12 12 12]
 [17 17 17 ... 12 12 12]
 [17 17 17 ... 12 11 11]
 ...
 [68 68 67 ...  1  0  0]
 [68 68 67 ...  1  0  0]
 [68 68 67 ...  1  0  0]]
[[132 132 132 ...  61  61  61]
 [132 132 132 ...  61  61  61]
 [132 132 132 ...  61  61  61]
 ...
 [ 25  25  25 ...  51  51  51]
 [ 25  25  25 ...  51  51  51]
 [ 25  25  25 ...  51  51  51]]
[[14 14 14 ... 13 13 13]
 [14 14 14 ... 13 13 13]
 [14 14 14 ... 13 12 12]
 ...
 [66 66 65 ...  1  2  2]
 [66 66

[[129 129 129 ...  59  59  59]
 [129 129 129 ...  59  59  59]
 [129 129 129 ...  59  59  59]
 ...
 [121 121 121 ...  50  50  50]
 [120 121 121 ...  50  50  50]
 [120 120 121 ...  50  50  50]]
[[17 17 17 ... 15 15 15]
 [17 17 17 ... 15 15 15]
 [17 17 17 ... 15 14 14]
 ...
 [30 30 31 ...  0  1  1]
 [29 30 31 ...  0  1  1]
 [29 29 31 ...  0  1  1]]
[[135 135 135 ...  60  59  59]
 [135 135 135 ...  60  59  59]
 [134 134 134 ...  60  59  59]
 ...
 [117 117 117 ...  49  49  49]
 [117 117 117 ...  49  49  49]
 [117 117 117 ...  49  49  49]]
[[11 11 11 ... 14 15 15]
 [11 11 11 ... 14 15 15]
 [12 12 12 ... 14 14 14]
 ...
 [26 26 27 ...  1  0  0]
 [26 26 27 ...  1  0  0]
 [26 26 27 ...  1  0  0]]
[[133 133 133 ...  60  60  60]
 [133 133 133 ...  60  60  60]
 [133 133 133 ...  60  60  60]
 ...
 [120 120 120 ...  51  51  51]
 [119 120 120 ...  51  51  51]
 [119 119 120 ...  51  51  51]]
[[13 13 13 ... 14 14 14]
 [13 13 13 ... 14 14 14]
 [13 13 13 ... 14 13 13]
 ...
 [29 29 30 ...  1  2  2]
 [28 29

[[130 130 130 ...  68  68  68]
 [130 130 130 ...  68  68  68]
 [130 130 130 ...  68  68  68]
 ...
 [120 120 120 ...  51  51  51]
 [120 120 120 ...  51  51  51]
 [120 120 120 ...  51  51  51]]
[[16 16 16 ...  6  6  6]
 [16 16 16 ...  6  6  6]
 [16 16 16 ...  6  5  5]
 ...
 [29 29 30 ...  1  2  2]
 [29 29 30 ...  1  2  2]
 [29 29 30 ...  1  2  2]]
[[132 132 132 ...  67  67  67]
 [132 132 132 ...  67  67  67]
 [132 132 132 ...  68  67  67]
 ...
 [118 118 118 ...  51  51  51]
 [118 118 118 ...  51  51  51]
 [118 118 118 ...  51  51  51]]
[[14 14 14 ...  7  7  7]
 [14 14 14 ...  7  7  7]
 [14 14 14 ...  6  6  6]
 ...
 [27 27 28 ...  1  2  2]
 [27 27 28 ...  1  2  2]
 [27 27 28 ...  1  2  2]]
[[132 132 132 ...  67  67  67]
 [132 132 132 ...  67  67  67]
 [132 132 132 ...  67  67  67]
 ...
 [120 120 120 ...  52  52  52]
 [120 120 120 ...  52  52  52]
 [120 120 120 ...  52  52  52]]
[[14 14 14 ...  7  7  7]
 [14 14 14 ...  7  7  7]
 [14 14 14 ...  7  6  6]
 ...
 [29 29 30 ...  2  3  3]
 [29 29

[[133 133 133 ...  63  63  63]
 [133 133 133 ...  63  63  63]
 [133 133 133 ...  63  63  63]
 ...
 [120 120 120 ...  52  52  52]
 [120 120 120 ...  52  52  52]
 [120 120 120 ...  52  52  52]]
[[13 13 13 ... 11 11 11]
 [13 13 13 ... 11 11 11]
 [13 13 13 ... 11 10 10]
 ...
 [29 29 30 ...  2  3  3]
 [29 29 30 ...  2  3  3]
 [29 29 30 ...  2  3  3]]
[[131 131 131 ...  61  61  61]
 [131 131 131 ...  62  61  61]
 [131 131 131 ...  62  62  61]
 ...
 [118 118 118 ...  52  52  52]
 [118 118 118 ...  52  52  52]
 [118 118 118 ...  52  52  52]]
[[15 15 15 ... 13 13 13]
 [15 15 15 ... 12 13 13]
 [15 15 15 ... 12 11 12]
 ...
 [27 27 28 ...  2  3  3]
 [27 27 28 ...  2  3  3]
 [27 27 28 ...  2  3  3]]
[[131 131 131 ...  70  69  69]
 [131 131 131 ...  70  69  69]
 [131 131 131 ...  70  70  70]
 ...
 [118 118 118 ...  55  55  55]
 [118 118 118 ...  55  55  55]
 [118 118 118 ...  55  55  54]]
[[15 15 15 ...  4  5  5]
 [15 15 15 ...  4  5  5]
 [15 15 15 ...  4  3  3]
 ...
 [27 27 28 ...  5  6  6]
 [27 27

[[133 133 133 ...  64  64  64]
 [133 133 133 ...  64  64  64]
 [133 133 133 ...  63  63  63]
 ...
 [117 117 117 ...  88  89  89]
 [116 116 117 ...  87  88  88]
 [116 116 116 ...  87  88  88]]
[[13 13 13 ... 10 10 10]
 [13 13 13 ... 10 10 10]
 [13 13 13 ... 11 10 10]
 ...
 [26 26 27 ... 38 40 40]
 [25 25 27 ... 37 39 39]
 [25 25 26 ... 37 39 39]]
[[133 133 133 ...  61  61  61]
 [133 133 133 ...  60  61  61]
 [133 133 133 ...  60  60  60]
 ...
 [116 116 116 ...  86  87  87]
 [116 116 116 ...  85  86  86]
 [116 116 116 ...  85  86  86]]
[[13 13 13 ... 13 13 13]
 [13 13 13 ... 14 13 13]
 [13 13 13 ... 14 13 13]
 ...
 [25 25 26 ... 36 38 38]
 [25 25 26 ... 35 37 37]
 [25 25 26 ... 35 37 37]]
[[132 132 132 ...  63  64  64]
 [132 132 132 ...  63  63  64]
 [132 132 132 ...  63  63  63]
 ...
 [117 117 117 ...  87  88  88]
 [117 117 117 ...  86  87  87]
 [117 117 117 ...  86  86  87]]
[[14 14 14 ... 11 10 10]
 [14 14 14 ... 11 11 10]
 [14 14 14 ... 11 10 10]
 ...
 [26 26 27 ... 37 39 39]
 [26 26

[[113 113 113 ...  55  55  55]
 [113 113 113 ...  55  55  55]
 [113 113 113 ...  55  55  55]
 ...
 [ 99  99  99 ...  77  76  76]
 [ 99  99  99 ...  78  77  77]
 [ 98  99  99 ...  78  77  77]]
[[33 33 33 ... 19 19 19]
 [33 33 33 ... 19 19 19]
 [33 33 33 ... 19 18 18]
 ...
 [ 8  8  9 ... 27 27 27]
 [ 8  8  9 ... 28 28 28]
 [ 7  8  9 ... 28 28 28]]
[[114 114 114 ...  54  54  54]
 [114 114 114 ...  54  54  54]
 [113 113 113 ...  53  54  54]
 ...
 [100 100 100 ...  85  85  85]
 [100 100 100 ...  86  86  86]
 [100 100 100 ...  87  86  86]]
[[32 32 32 ... 20 20 20]
 [32 32 32 ... 20 20 20]
 [33 33 33 ... 21 19 19]
 ...
 [ 9  9 10 ... 35 36 36]
 [ 9  9 10 ... 36 37 37]
 [ 9  9 10 ... 37 37 37]]
[[115 115 115 ...  53  53  53]
 [115 115 115 ...  53  53  53]
 [115 115 115 ...  53  53  53]
 ...
 [101 101 101 ...  89  89  89]
 [101 101 101 ...  90  90  90]
 [101 101 101 ...  90  90  90]]
[[31 31 31 ... 21 21 21]
 [31 31 31 ... 21 21 21]
 [31 31 31 ... 21 20 20]
 ...
 [10 10 11 ... 39 40 40]
 [10 10

[[113 113 113 ...  49  49  49]
 [113 113 113 ...  49  49  49]
 [113 113 113 ...  49  49  49]
 ...
 [100 100 100 ...  81  82  82]
 [100 100 100 ...  80  81  81]
 [100 100 100 ...  80  81  81]]
[[33 33 33 ... 25 25 25]
 [33 33 33 ... 25 25 25]
 [33 33 33 ... 25 24 24]
 ...
 [ 9  9 10 ... 31 33 33]
 [ 9  9 10 ... 30 32 32]
 [ 9  9 10 ... 30 32 32]]
[[114 114 113 ...  47  47  47]
 [114 114 113 ...  47  47  47]
 [113 113 113 ...  47  47  47]
 ...
 [ 99  99  99 ...  80  81  82]
 [ 99  99  99 ...  80  81  81]
 [ 99  99  99 ...  79  80  81]]
[[32 32 33 ... 27 27 27]
 [32 32 33 ... 27 27 27]
 [33 33 33 ... 27 26 26]
 ...
 [ 8  8  9 ... 30 32 33]
 [ 8  8  9 ... 30 32 32]
 [ 8  8  9 ... 29 31 32]]
[[114 114 113 ...  48  47  47]
 [114 114 113 ...  48  47  47]
 [113 113 113 ...  47  47  47]
 ...
 [100 100 100 ...  81  82  82]
 [100 100 100 ...  80  81  81]
 [100 100 100 ...  80  81  81]]
[[32 32 33 ... 26 27 27]
 [32 32 33 ... 26 27 27]
 [33 33 33 ... 27 26 26]
 ...
 [ 9  9 10 ... 31 33 33]
 [ 9  9

[[114 114 114 ...  46  46  46]
 [114 114 114 ...  46  46  46]
 [114 114 114 ...  46  46  46]
 ...
 [ 99  99  99 ...  66  66  65]
 [ 99  99  99 ...  66  65  65]
 [ 99  98  98 ...  66  65  65]]
[[32 32 32 ... 28 28 28]
 [32 32 32 ... 28 28 28]
 [32 32 32 ... 28 27 27]
 ...
 [ 8  8  9 ... 16 17 16]
 [ 8  8  9 ... 16 16 16]
 [ 8  7  8 ... 16 16 16]]
[[113 113 113 ...  44  44  44]
 [113 113 113 ...  44  44  44]
 [113 113 113 ...  44  44  44]
 ...
 [ 99  99  99 ...  69  69  69]
 [ 99  99  99 ...  69  69  69]
 [ 99  99  99 ...  69  69  69]]
[[33 33 33 ... 30 30 30]
 [33 33 33 ... 30 30 30]
 [33 33 33 ... 30 29 29]
 ...
 [ 8  8  9 ... 19 20 20]
 [ 8  8  9 ... 19 20 20]
 [ 8  8  9 ... 19 20 20]]
[[113 113 113 ...  45  45  45]
 [113 113 113 ...  45  45  45]
 [113 113 113 ...  45  45  45]
 ...
 [ 99  99  99 ...  67  66  66]
 [ 99  99  99 ...  67  66  66]
 [ 99  99  99 ...  67  66  66]]
[[33 33 33 ... 29 29 29]
 [33 33 33 ... 29 29 29]
 [33 33 33 ... 29 28 28]
 ...
 [ 8  8  9 ... 17 17 17]
 [ 8  8

[[33 33 33 ... 27 27 27]
 [33 33 33 ... 27 27 27]
 [34 34 34 ... 27 27 27]
 ...
 [ 9  9  9 ... 35 38 38]
 [ 8  8  9 ... 35 37 38]
 [ 8  8  9 ... 35 37 38]]
[[112 112 112 ...  46  46  46]
 [112 112 112 ...  46  46  46]
 [112 112 112 ...  45  45  46]
 ...
 [100 100 100 ...  91  93  93]
 [100 100 100 ...  91  92  93]
 [100 100 100 ...  91  92  93]]
[[34 34 34 ... 28 28 28]
 [34 34 34 ... 28 28 28]
 [34 34 34 ... 29 28 27]
 ...
 [ 9  9 10 ... 41 44 44]
 [ 9  9 10 ... 41 43 44]
 [ 9  9 10 ... 41 43 44]]
[[115 115 115 ...  47  47  47]
 [114 114 114 ...  47  47  47]
 [114 114 114 ...  47  47  47]
 ...
 [100 100 100 ...  88  89  89]
 [100 100 100 ...  88  89  90]
 [100 100 100 ...  88  89  90]]
[[31 31 31 ... 27 27 27]
 [32 32 32 ... 27 27 27]
 [32 32 32 ... 27 26 26]
 ...
 [ 9  9 10 ... 38 40 40]
 [ 9  9 10 ... 38 40 41]
 [ 9  9 10 ... 38 40 41]]
[[113 113 113 ...  51  51  51]
 [113 113 113 ...  51  51  51]
 [112 112 112 ...  50  51  51]
 ...
 [100 100 100 ...  92  93  93]
 [100 100 100 ...  

[[113 113 113 ...  49  49  49]
 [113 113 113 ...  49  49  49]
 [113 113 113 ...  48  48  48]
 ...
 [101 101 101 ...  91  92  93]
 [101 101 100 ...  92  93  93]
 [101 100 100 ...  92  93  93]]
[[33 33 33 ... 25 25 25]
 [33 33 33 ... 25 25 25]
 [33 33 33 ... 26 25 25]
 ...
 [10 10 11 ... 41 43 44]
 [10 10 10 ... 42 44 44]
 [10  9 10 ... 42 44 44]]
[[114 114 114 ...  51  51  51]
 [114 114 114 ...  51  51  51]
 [114 114 114 ...  51  51  51]
 ...
 [100 100 100 ...  88  89  90]
 [100 100 100 ...  88  89  90]
 [100 100 100 ...  88  90  90]]
[[32 32 32 ... 23 23 23]
 [32 32 32 ... 23 23 23]
 [32 32 32 ... 23 22 22]
 ...
 [ 9  9 10 ... 38 40 41]
 [ 9  9 10 ... 38 40 41]
 [ 9  9 10 ... 38 41 41]]
[[113 113 113 ...  51  51  51]
 [113 113 113 ...  51  51  51]
 [113 113 113 ...  51  51  51]
 ...
 [ 99 100 100 ...  86  86  87]
 [ 99  99 100 ...  85  86  87]
 [ 99  99  99 ...  85  86  87]]
[[33 33 33 ... 23 23 23]
 [33 33 33 ... 23 23 23]
 [33 33 33 ... 23 22 22]
 ...
 [ 8  9 10 ... 36 37 38]
 [ 8  8

[[112 113 113 ...  51  51  52]
 [112 112 113 ...  51  51  51]
 [112 112 112 ...  51  51  51]
 ...
 [100 100 100 ...  82  83  84]
 [100 100 100 ...  82  83  84]
 [100 100 100 ...  82  83  83]]
[[34 33 33 ... 23 23 22]
 [34 34 33 ... 23 23 23]
 [34 34 34 ... 23 22 22]
 ...
 [ 9  9 10 ... 32 34 35]
 [ 9  9 10 ... 32 34 35]
 [ 9  9 10 ... 32 34 34]]
[[113 113 113 ...  51  52  52]
 [113 113 113 ...  51  52  52]
 [113 113 113 ...  51  51  51]
 ...
 [ 98  98  98 ...  81  82  83]
 [ 98  98  98 ...  81  82  82]
 [ 98  98  98 ...  81  82  82]]
[[33 33 33 ... 23 22 22]
 [33 33 33 ... 23 22 22]
 [33 33 33 ... 23 22 22]
 ...
 [ 7  7  8 ... 31 33 34]
 [ 7  7  8 ... 31 33 33]
 [ 7  7  8 ... 31 33 33]]
[[112 112 112 ...  53  54  54]
 [112 112 112 ...  53  53  54]
 [112 112 112 ...  53  53  53]
 ...
 [100 100 100 ...  84  85  85]
 [100 100 100 ...  83  84  85]
 [100 100 100 ...  83  84  84]]
[[34 34 34 ... 21 20 20]
 [34 34 34 ... 21 21 20]
 [34 34 34 ... 21 20 20]
 ...
 [ 9  9 10 ... 34 36 36]
 [ 9  9

[[114 114 114 ...  49  49  49]
 [114 114 114 ...  49  49  49]
 [113 113 113 ...  49  49  49]
 ...
 [ 99  99  99 ...  97  98  99]
 [ 98  98  99 ...  96  97  98]
 [ 98  98  99 ...  96  97  98]]
[[32 32 32 ... 25 25 25]
 [32 32 32 ... 25 25 25]
 [33 33 33 ... 25 24 24]
 ...
 [ 8  8  9 ... 47 49 50]
 [ 7  7  9 ... 46 48 49]
 [ 7  7  9 ... 46 48 49]]
[[112 112 112 ...  48  49  49]
 [112 112 112 ...  48  48  48]
 [112 112 112 ...  48  48  48]
 ...
 [101 101 101 ...  99 101 101]
 [101 101 101 ...  99 100 100]
 [100 100 100 ...  98 100 100]]
[[34 34 34 ... 26 25 25]
 [34 34 34 ... 26 26 26]
 [34 34 34 ... 26 25 25]
 ...
 [10 10 11 ... 49 52 52]
 [10 10 11 ... 49 51 51]
 [ 9  9 10 ... 48 51 51]]
[[114 114 114 ...  50  50  51]
 [114 114 114 ...  50  50  50]
 [114 114 114 ...  50  50  50]
 ...
 [ 98  98  98 ...  97  98  98]
 [ 98  98  98 ...  96  98  98]
 [ 98  98  98 ...  96  97  98]]
[[32 32 32 ... 24 24 23]
 [32 32 32 ... 24 24 24]
 [32 32 32 ... 24 23 23]
 ...
 [ 7  7  8 ... 47 49 49]
 [ 7  7

[[112 113 113 ...  46  46  46]
 [112 113 113 ...  46  46  46]
 [112 113 113 ...  46  46  46]
 ...
 [ 99  99  99 ...  80  80  80]
 [ 99  99  99 ...  80  79  79]
 [ 99  99  99 ...  79  79  79]]
[[34 33 33 ... 28 28 28]
 [34 33 33 ... 28 28 28]
 [34 33 33 ... 28 27 27]
 ...
 [ 8  8  9 ... 30 31 31]
 [ 8  8  9 ... 30 30 30]
 [ 8  8  9 ... 29 30 30]]
[[116 116 115 ...  47  47  47]
 [116 115 115 ...  47  47  47]
 [115 115 115 ...  47  47  47]
 ...
 [ 97  97  97 ...  80  79  79]
 [ 97  97  97 ...  79  79  78]
 [ 97  97  97 ...  79  79  78]]
[[30 30 31 ... 27 27 27]
 [30 31 31 ... 27 27 27]
 [31 31 31 ... 27 26 26]
 ...
 [ 6  6  7 ... 30 30 30]
 [ 6  6  7 ... 29 30 29]
 [ 6  6  7 ... 29 30 29]]
[[113 113 113 ...  48  48  48]
 [113 113 113 ...  48  48  48]
 [113 113 113 ...  48  48  48]
 ...
 [101 101 101 ...  84  83  83]
 [101 101 101 ...  84  83  83]
 [101 101 101 ...  84  83  83]]
[[33 33 33 ... 26 26 26]
 [33 33 33 ... 26 26 26]
 [33 33 33 ... 26 25 25]
 ...
 [10 10 11 ... 34 34 34]
 [10 10

[[112 112 112 ...  47  47  47]
 [112 112 112 ...  47  47  47]
 [112 112 112 ...  47  47  47]
 ...
 [ 98  98  98 ...  98  96  96]
 [ 98  98  98 ...  98  97  96]
 [ 98  98  98 ...  99  97  97]]
[[34 34 34 ... 27 27 27]
 [34 34 34 ... 27 27 27]
 [34 34 34 ... 27 26 26]
 ...
 [ 7  7  8 ... 48 47 47]
 [ 7  7  8 ... 48 48 47]
 [ 7  7  8 ... 49 48 48]]
[[113 113 113 ...  48  48  48]
 [113 113 113 ...  48  48  48]
 [113 113 113 ...  47  47  47]
 ...
 [100 100 100 ... 106 105 104]
 [100 100 100 ... 107 106 105]
 [100 100 100 ... 107 106 105]]
[[33 33 33 ... 26 26 26]
 [33 33 33 ... 26 26 26]
 [33 33 33 ... 27 26 26]
 ...
 [ 9  9 10 ... 56 56 55]
 [ 9  9 10 ... 57 57 56]
 [ 9  9 10 ... 57 57 56]]
[[113 113 113 ...  47  47  47]
 [113 113 113 ...  47  47  47]
 [113 113 113 ...  46  46  46]
 ...
 [ 98  98  98 ... 108 107 107]
 [ 98  98  98 ... 109 108 107]
 [ 98  98  98 ... 109 108 108]]
[[33 33 33 ... 27 27 27]
 [33 33 33 ... 27 27 27]
 [33 33 33 ... 28 27 27]
 ...
 [ 7  7  8 ... 58 58 58]
 [ 7  7

[[113 113 113 ...  52  52  52]
 [113 113 113 ...  52  52  52]
 [113 113 113 ...  52  52  52]
 ...
 [101 101 101 ... 121 122 123]
 [101 101 101 ... 121 122 122]
 [101 101 101 ... 121 122 122]]
[[33 33 33 ... 22 22 22]
 [33 33 33 ... 22 22 22]
 [33 33 33 ... 22 21 21]
 ...
 [10 10 11 ... 71 73 74]
 [10 10 11 ... 71 73 73]
 [10 10 11 ... 71 73 73]]
[[112 113 113 ...  51  51  51]
 [112 113 113 ...  51  51  51]
 [112 112 113 ...  51  51  51]
 ...
 [ 98  98  98 ... 118 119 119]
 [ 98  98  98 ... 117 118 119]
 [ 98  98  98 ... 117 118 118]]
[[34 33 33 ... 23 23 23]
 [34 33 33 ... 23 23 23]
 [34 34 33 ... 23 22 22]
 ...
 [ 7  7  8 ... 68 70 70]
 [ 7  7  8 ... 67 69 70]
 [ 7  7  8 ... 67 69 69]]
[[114 114 114 ...  51  51  51]
 [114 114 114 ...  51  51  51]
 [114 114 114 ...  51  51  51]
 ...
 [100 100 100 ... 123 124 124]
 [100 100 100 ... 123 124 124]
 [100 100 100 ... 122 123 124]]
[[32 32 32 ... 23 23 23]
 [32 32 32 ... 23 23 23]
 [32 32 32 ... 23 22 22]
 ...
 [ 9  9 10 ... 73 75 75]
 [ 9  9

[[114 114 114 ...  44  44  44]
 [114 114 114 ...  44  44  44]
 [114 114 114 ...  44  44  44]
 ...
 [100 100 100 ...  89  88  87]
 [ 99  99  99 ...  89  88  88]
 [ 99  99  99 ...  90  88  88]]
[[32 32 32 ... 30 30 30]
 [32 32 32 ... 30 30 30]
 [32 32 32 ... 30 29 29]
 ...
 [ 9  9 10 ... 39 39 38]
 [ 8  8  9 ... 39 39 39]
 [ 8  8  9 ... 40 39 39]]
[[113 113 113 ...  46  46  46]
 [113 113 113 ...  46  46  46]
 [113 113 113 ...  46  46  46]
 ...
 [102 102 102 ...  90  89  89]
 [102 102 102 ...  91  89  89]
 [102 102 102 ...  91  90  89]]
[[33 33 33 ... 28 28 28]
 [33 33 33 ... 28 28 28]
 [33 33 33 ... 28 27 27]
 ...
 [11 11 12 ... 40 40 40]
 [11 11 12 ... 41 40 40]
 [11 11 12 ... 41 41 40]]
[[113 113 113 ...  44  44  44]
 [113 113 113 ...  44  44  44]
 [113 113 113 ...  44  44  44]
 ...
 [101 101 101 ...  89  88  88]
 [101 101 101 ...  90  88  88]
 [101 101 101 ...  90  89  88]]
[[33 33 33 ... 30 30 30]
 [33 33 33 ... 30 30 30]
 [33 33 33 ... 30 29 29]
 ...
 [10 10 11 ... 39 39 39]
 [10 10

[[112 112 112 ...  46  46  46]
 [112 112 112 ...  46  46  46]
 [112 112 112 ...  46  46  46]
 ...
 [101 101 101 ...  87  88  89]
 [101 101 101 ...  86  88  88]
 [101 101 101 ...  86  87  88]]
[[34 34 34 ... 28 28 28]
 [34 34 34 ... 28 28 28]
 [34 34 34 ... 28 27 27]
 ...
 [10 10 11 ... 37 39 40]
 [10 10 11 ... 36 39 39]
 [10 10 11 ... 36 38 39]]
[[112 112 112 ...  49  49  49]
 [112 112 112 ...  49  49  49]
 [112 112 112 ...  49  49  49]
 ...
 [100 100 100 ...  84  85  85]
 [100 100 100 ...  83  84  85]
 [100 100 100 ...  83  84  84]]
[[34 34 34 ... 25 25 25]
 [34 34 34 ... 25 25 25]
 [34 34 34 ... 25 24 24]
 ...
 [ 9  9 10 ... 34 36 36]
 [ 9  9 10 ... 33 35 36]
 [ 9  9 10 ... 33 35 35]]
[[112 113 113 ...  53  53  53]
 [112 113 113 ...  53  53  53]
 [112 112 113 ...  53  53  53]
 ...
 [100 100 100 ...  86  87  87]
 [100 100 100 ...  85  86  86]
 [100 100 100 ...  84  86  86]]
[[34 33 33 ... 21 21 21]
 [34 33 33 ... 21 21 21]
 [34 34 33 ... 21 20 20]
 ...
 [ 9  9 10 ... 36 38 38]
 [ 9  9

[[112 112 112 ...  52  52  52]
 [112 112 112 ...  52  52  52]
 [112 112 112 ...  52  52  52]
 ...
 [ 99  99  99 ...  28  28  28]
 [ 98  98  99 ...  28  28  28]
 [ 98  98  98 ...  28  28  28]]
[[34 34 34 ... 22 22 22]
 [34 34 34 ... 22 22 22]
 [34 34 34 ... 22 21 21]
 ...
 [ 8  8  9 ... 22 21 21]
 [ 7  7  9 ... 22 21 21]
 [ 7  7  8 ... 22 21 21]]
[[114 114 114 ...  55  55  55]
 [114 114 114 ...  55  55  55]
 [114 114 114 ...  55  55  55]
 ...
 [100 100 100 ...  28  28  28]
 [100 100 100 ...  28  28  28]
 [100 100 100 ...  28  28  28]]
[[32 32 32 ... 19 19 19]
 [32 32 32 ... 19 19 19]
 [32 32 32 ... 19 18 18]
 ...
 [ 9  9 10 ... 22 21 21]
 [ 9  9 10 ... 22 21 21]
 [ 9  9 10 ... 22 21 21]]
[[112 112 112 ...  52  52  52]
 [112 112 112 ...  52  52  52]
 [112 112 112 ...  52  52  52]
 ...
 [101 101 101 ...  28  28  28]
 [101 101 101 ...  28  28  28]
 [101 101 101 ...  28  28  28]]
[[34 34 34 ... 22 22 22]
 [34 34 34 ... 22 22 22]
 [34 34 34 ... 22 21 21]
 ...
 [10 10 11 ... 22 21 21]
 [10 10

In [2]:
import cv2
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
video = cv2.VideoCapture(0)
img = cv2.imread('group.jpg')
gry_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gry_img,scaleFactor=1.05,minNeighbors=12)
for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),1)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import cv2
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
video = cv2.VideoCapture(0)
while True:
    check,frame= video.read()
    grey = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(grey,1.03,5)
    for x,y,w,h in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
    cv2.imshow('Live...',frame)
    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()

In [7]:
# Pyhton program to implement 
# WebCam Motion Detector
 
# importing OpenCV, time and Pandas library
import cv2, time, pandas
# importing datetime class from datetime library
from datetime import datetime
 
# Assigning our static_back to None
static_back = None
 
# List when any moving object appear
motion_list = [ None, None ]
 
# Time of movement
time = []
 
# Initializing DataFrame, one column is start 
# time and other column is end time
df = pandas.DataFrame(columns = ["Start", "End"])
 
# Capturing video
video = cv2.VideoCapture(0)
 
# Infinite while loop to treat stack of image as video
while True:
    # Reading frame(image) from video
    check, frame = video.read()
 
    # Initializing motion = 0(no motion)
    motion = 0
 
    # Converting color image to gray_scale image
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
 
    # Converting gray scale image to GaussianBlur 
    # so that change can be find easily
    gray = cv2.GaussianBlur(gray, (21, 21), 0)
 
    # In first iteration we assign the value 
    # of static_back to our first frame
    if static_back is None:
        static_back = gray
        continue
 
    # Difference between static background 
    # and current frame(which is GaussianBlur)
    diff_frame = cv2.absdiff(static_back, gray)
 
    # If change in between static background and
    # current frame is greater than 30 it will show white color(255)
    thresh_frame = cv2.threshold(diff_frame, 30, 255, cv2.THRESH_BINARY)[1]
    thresh_frame = cv2.dilate(thresh_frame, None, iterations = 2)
 
    # Finding contour of moving object
    (_, cnts, _) = cv2.findContours(thresh_frame.copy(), 
                       cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
 
    for contour in cnts:
        if cv2.contourArea(contour) < 10000:
            continue
        motion = 1
 
        (x, y, w, h) = cv2.boundingRect(contour)
        # making green rectangle arround the moving object
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)
 
    # Appending status of motion
    motion_list.append(motion)
 
    motion_list = motion_list[-2:]
 
    # Appending Start time of motion
    if motion_list[-1] == 1 and motion_list[-2] == 0:
        time.append(datetime.now())
 
    # Appending End time of motion
    if motion_list[-1] == 0 and motion_list[-2] == 1:
        time.append(datetime.now())
 
    # Displaying image in gray_scale
    cv2.imshow("Gray Frame", gray)
 
    # Displaying the difference in currentframe to
    # the staticframe(very first_frame)
    cv2.imshow("Difference Frame", diff_frame)
 
    # Displaying the black and white image in which if
    # intencity difference greater than 30 it will appear white
    cv2.imshow("Threshold Frame", thresh_frame)
 
    # Displaying color frame with contour of motion of object
    cv2.imshow("Color Frame", frame)
 
    key = cv2.waitKey(1)
    # if q entered whole process will stop
    if key == ord('q'):
        # if something is movingthen it append the end time of movement
        if motion == 1:
            time.append(datetime.now())
        break
 
# Appending time of motion in DataFrame
for i in range(0, len(time), 2):
    df = df.append({"Start":time[i], "End":time[i + 1]}, ignore_index = True)
 
# Creating a csv file in which time of movements will be saved
df.to_csv("Time_of_movements.csv")
 
video.release()
 
# Destroying all the windows
cv2.destroyAllWindows()